---
# tasks file for lorenzobettini.my_nerd_fonts_role
- name: Ensure ca-certificates is present
  become: true
  ansible.builtin.package:
    state: present
    name:
    - ca-certificates

- name: Ensure fc-cache is present
  become: true
  ansible.builtin.package:
    state: present
    name:
    - fontconfig

- name: Override xz package name for Debian.
  ansible.builtin.set_fact:
    xz_package: xz-utils
  when: ansible_os_family == 'Debian'

# unzip is useful for extracting zips
- name: Install unzip and other compression utilities
  become: true
  ansible.builtin.package:
    state: present
    name:
    - unzip
    - "{{ xz_package }}"

- name: Download and extract fonts to fonts directory.
  include_tasks: "download-font.yml"
  loop: "{{ fonts_to_install }}"
  loop_control:
    loop_var: font

- name: Update font cache
  ansible.builtin.shell: fc-cache -f
  changed_when: false
