---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
  - name: List fonts
    ansible.builtin.shell: "fc-list : family spacing"
    register: font_list
    args:
      executable: /bin/bash
    changed_when: false

  - name: Assert JetBrainsMono is installed
    ansible.builtin.assert:
      that: "'JetBrainsMono Nerd' in font_list.stdout"
